name: GitLab Contributions
run-name: Synchronize Contributions

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  GITLAB_SERVER_URL: ${{ secrets.GITLAB_SERVER_URL }}
  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}

jobs:
  import:
    name: Import Contributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Import Contributions
        run: python gitlab-contributions.py
