name: Import GitLab Contributions

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI_SERVER_URL: ${{ secrets.CI_SERVER_URL }}
  CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}

permissions: read-all

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python gitlab-contributions.py
